### ISSUE TITLE
Writing to /etc/hosts fails on OSX 

### ISSUE THREAD

**Issue by k1sul1** [Seravo/wp-vagrant#24]
When running vagrant up, the command fails with this chunk of text:

```
Bringing machine 'sample-box' up with 'virtualbox' provider...
==> sample-box: Checking if box 'seravo/wordpress' is up to date...
==> sample-box: VirtualBox VM is already running.
==> sample-box: [vagrant-hostsupdater] Checking for host entries
==> sample-box: [vagrant-hostsupdater] Writing the following entries to (/etc/hosts)
==> sample-box: [vagrant-hostsupdater]   192.168.93.139  sample  # VAGRANT: 799c4eac34e80adc79c99df966b0587a (sample-box) / b22a5436-f033-4008-8264-1b041bc11c78
==> sample-box: [vagrant-hostsupdater]   192.168.93.139  sample.local  # VAGRANT: 799c4eac34e80adc79c99df966b0587a (sample-box) / b22a5436-f033-4008-8264-1b041bc11c78
==> sample-box: [vagrant-hostsupdater]   192.168.93.139  www.sample.local  # VAGRANT: 799c4eac34e80adc79c99df966b0587a (sample-box) / b22a5436-f033-4008-8264-1b041bc11c78
==> sample-box: [vagrant-hostsupdater]   192.168.93.139  webgrind.sample.local  # VAGRANT: 799c4eac34e80adc79c99df966b0587a (sample-box) / b22a5436-f033-4008-8264-1b041bc11c78
==> sample-box: [vagrant-hostsupdater]   192.168.93.139  adminer.sample.local  # VAGRANT: 799c4eac34e80adc79c99df966b0587a (sample-box) / b22a5436-f033-4008-8264-1b041bc11c78
==> sample-box: [vagrant-hostsupdater]   192.168.93.139  mailcatcher.sample.local  # VAGRANT: 799c4eac34e80adc79c99df966b0587a (sample-box) / b22a5436-f033-4008-8264-1b041bc11c78
==> sample-box: [vagrant-hostsupdater]   192.168.93.139  browsersync.sample.local  # VAGRANT: 799c4eac34e80adc79c99df966b0587a (sample-box) / b22a5436-f033-4008-8264-1b041bc11c78
==> sample-box: [vagrant-hostsupdater]   192.168.93.139  info.sample.local  # VAGRANT: 799c4eac34e80adc79c99df966b0587a (sample-box) / b22a5436-f033-4008-8264-1b041bc11c78
==> sample-box: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.
/Users/christian/.vagrant.d/gems/gems/vagrant-hostsupdater-1.0.2/lib/vagrant-hostsupdater/HostsUpdater.rb:98:in `initialize': Permission denied @ rb_sysopen - /etc/hosts (Errno::EACCES)
    from /Users/christian/.vagrant.d/gems/gems/vagrant-hostsupdater-1.0.2/lib/vagrant-hostsupdater/HostsUpdater.rb:98:in `open'
    from /Users/christian/.vagrant.d/gems/gems/vagrant-hostsupdater-1.0.2/lib/vagrant-hostsupdater/HostsUpdater.rb:98:in `addToHosts'
    from /Users/christian/.vagrant.d/gems/gems/vagrant-hostsupdater-1.0.2/lib/vagrant-hostsupdater/HostsUpdater.rb:47:in `addHostEntries'
    from /Users/christian/.vagrant.d/gems/gems/vagrant-hostsupdater-1.0.2/lib/vagrant-hostsupdater/Action/UpdateHosts.rb:17:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/message_already_running.rb:11:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/box_check_outdated.rb:78:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builtin/call.rb:53:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /Users/christian/.vagrant.d/gems/gems/vagrant-triggers-0.5.3/lib/vagrant-triggers/action/trigger.rb:17:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /Users/christian/.vagrant.d/gems/gems/vagrant-triggers-0.5.3/lib/vagrant-triggers/action/trigger.rb:17:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /Users/christian/.vagrant.d/gems/gems/vagrant-triggers-0.5.3/lib/vagrant-triggers/action/trigger.rb:17:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/warden.rb:34:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/builder.rb:116:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `block in run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/busy.rb:19:in `busy'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/action/runner.rb:66:in `run'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:224:in `action_raw'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:199:in `block in action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/environment.rb:561:in `lock'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

Basically for some reason it's unable to write to the hosts file, and I have to add the entries manually. Removing seems to happen just fine on vagrant halt. It never asks for a password to gain administrator privileges, but I can write to /etc/hosts just fine without root. 

Kinda annoying having to do this every time.

**Comment by anttiviljami** [comment]
It doesn't ask for sudo for you ?

**Comment by anttiviljami** [comment]
Must be a bug with your version of vagrant-hostsupdater. Not really related to Seravo/wp-palvelu-vagrant. Could also be a Vagrantfile issue in Seravo/wordpress

Here's what I'm getting with the most recent version of Seravo/wordpress.

```
==> wordpress-box: Checking for host entries
==> wordpress-box: adding to (/etc/hosts) : 192.168.85.119  wordpress  # VAGRANT: ca9d4dccafaa69cfd97420a7015f85ea (wordpress-box) / 64a6117c-de1f-4889-8b10-68734fa53df8
==> wordpress-box: adding to (/etc/hosts) : 192.168.85.119  wordpress.local  # VAGRANT: ca9d4dccafaa69cfd97420a7015f85ea (wordpress-box) / 64a6117c-de1f-4889-8b10-68734fa53df8
==> wordpress-box: adding to (/etc/hosts) : 192.168.85.119  www.wordpress.local  # VAGRANT: ca9d4dccafaa69cfd97420a7015f85ea (wordpress-box) / 64a6117c-de1f-4889-8b10-68734fa53df8
==> wordpress-box: adding to (/etc/hosts) : 192.168.85.119  webgrind.wordpress.local  # VAGRANT: ca9d4dccafaa69cfd97420a7015f85ea (wordpress-box) / 64a6117c-de1f-4889-8b10-68734fa53df8
==> wordpress-box: adding to (/etc/hosts) : 192.168.85.119  adminer.wordpress.local  # VAGRANT: ca9d4dccafaa69cfd97420a7015f85ea (wordpress-box) / 64a6117c-de1f-4889-8b10-68734fa53df8
==> wordpress-box: adding to (/etc/hosts) : 192.168.85.119  mailcatcher.wordpress.local  # VAGRANT: ca9d4dccafaa69cfd97420a7015f85ea (wordpress-box) / 64a6117c-de1f-4889-8b10-68734fa53df8
==> wordpress-box: adding to (/etc/hosts) : 192.168.85.119  browsersync.wordpress.local  # VAGRANT: ca9d4dccafaa69cfd97420a7015f85ea (wordpress-box) / 64a6117c-de1f-4889-8b10-68734fa53df8
==> wordpress-box: adding to (/etc/hosts) : 192.168.85.119  info.wordpress.local  # VAGRANT: ca9d4dccafaa69cfd97420a7015f85ea (wordpress-box) / 64a6117c-de1f-4889-8b10-68734fa53df8

WARNING: Improper use of the sudo command could lead to data loss
or the deletion of important system files. Please double-check your
typing when using sudo. Type "man sudo" for more information.

To proceed, enter your password, or type Ctrl-C to abort.

Password:
==> wordpress-box: Setting hostname...
```

**Comment by k1sul1** [comment]
Yeah, it doesn't ask for sudo. Might be worth noting that sudo is granted automatically for me (without password), but that can't be the cause right? 

I also thought that it could be a bug with vagrant-hostsupdater, but updating it to the latest version didn't really change anything.

**Comment by anttiviljami** [comment]
can you give me your output for

```
vagrant --version
vagrant plugin list
```

**Comment by k1sul1** [comment]
Sure: 

```
vagrant --version
Vagrant 1.8.1
```

```
vagrant plugin list
vagrant-bindfs (0.4.9)
vagrant-hostmanager (1.8.5)
vagrant-hostsupdater (1.0.2)
vagrant-share (1.1.5, system)
vagrant-triggers (0.5.3)
```

```
vagrant plugin update hostmanager
Updating plugins: hostmanager. This may take a few minutes...
All plugins are up to date.
```

**Comment by anttiviljami** [comment]
Vagrantfile uses hostsupdater, not hostsmanager. :)

Where did you get version 1.0.2 of vagrant-hostsupdater? The newest I can find is 0.0.11

**Comment by k1sul1** [comment]
Just `vagrant plugin install vagrant-hostsupdater`?

vagrant plugin install vagrant-hostsupdater
Installing the 'vagrant-hostsupdater' plugin. This can take a few minutes...
Installed the plugin 'vagrant-hostsupdater (1.0.2)!

**Comment by k1sul1** [comment]
Weird. After running `vagrant plugin install vagrant-hostsupdater` again, `vagrant up` actually worked without complaining. 

You can probably close this as PEBKAC.

**Comment by anttiviljami** [comment]
fascinating. :)

**Comment by k1sul1** [comment]
I'm not exactly sure why this happened again, but it did. I got the same error-block by running vagrant up, but this time `vagrant plugin install vagrant-hostsupdater` doesn't do anything to fix the problem. 

For some reason it is unable to open /etc/hosts. It should prompt for sudo (which it would be granted automatically), but it doesn't, just fails and stops the machine. Might be worth noting that I can write to /etc/hosts without sudo, but when saving the file in vim, it says `"/private/etc/hosts" 10L, 214C written`. 

I'll try rebooting my machine and see if it magically fixes every problem in the universe.

**Comment by k1sul1** [comment]
Well it didn't fix every problem in the universe, but it seems that it fixed this one.

**Comment by anttiviljami** [comment]
I dont think there's anything special about our hostsupdater configuration in Seravo/wordpress. Must be a general Vagrant issue i'm afraid
