### ISSUE TITLE
wp cli update should be run when provisioning a box

### ISSUE THREAD

**Issue by k1sul1** [Seravo/wp-vagrant#27]
Fresh wp-palvelu.fi site, cloned from "production" with 

`git clone ssh://user@site.seravo.fi:6666/data/wordpress ./sitename --origin production`

and then nothing else but `cd sitename; vagrant up`. The script will eventually prompt about cloning the production database, and if you answer "y" to it, it will fail. 

```
Removed wp-content from core and symlinked it to ../wp-content
    censored-box: Pull database from production? (no): y
==> censored-box: Executing remote command "wp-pull-production-db"...
==> censored-box: Saving backup of current development database in /data/db/pre-production-pull-backup.sql...
==> censored-box: Success: Exported to pre-production-pull-backup-1475666834.sql
==> censored-box: Define new and old siteurl for later search-replacing...
==> censored-box: PHP Fatal error:  Uncaught Error: Call to undefined function apply_filters() in /data/wordpress/htdocs/wordpress/wp-includes/load.php:317
==> censored-box: Stack trace:
==> censored-box: #0 phar:///usr/local/bin/wp-cli/php/utils-wp.php(22): wp_debug_mode()
==> censored-box: #1 phar:///usr/local/bin/wp-cli/php/wp-settings-cli.php(59): WP_CLI\Utils\wp_debug_mode()
==> censored-box: #2 phar:///usr/local/bin/wp-cli/php/WP_CLI/Runner.php(807): require('phar:///usr/loc...')
==> censored-box: #3 phar:///usr/local/bin/wp-cli/php/WP_CLI/Runner.php(755): WP_CLI\Runner->load_wordpress()
==> censored-box: #4 phar:///usr/local/bin/wp-cli/php/wp-cli.php(21): WP_CLI\Runner->start()
==> censored-box: #5 phar:///usr/local/bin/wp-cli/php/boot-phar.php(5): include('phar:///usr/loc...')
==> censored-box: #6 /usr/local/bin/wp-cli(4): include('phar:///usr/loc...')
==> censored-box: #7 {main}
==> censored-box:   thrown in /data/wordpress/htdocs/wordpress/wp-includes/load.php on line 317
==> censored-box: Pulling database from production with 'wp db export'...
==> censored-box: Success: Imported from -
==> censored-box: Search-replacing  with  --skip-columns=guid
==> censored-box: PHP Fatal error:  Uncaught Error: Call to undefined function apply_filters() in /data/wordpress/htdocs/wordpress/wp-includes/load.php:317
==> censored-box: Stack trace:
==> censored-box: #0 phar:///usr/local/bin/wp-cli/php/utils-wp.php(22): wp_debug_mode()
==> censored-box: #1 phar:///usr/local/bin/wp-cli/php/wp-settings-cli.php(59): WP_CLI\Utils\wp_debug_mode()
==> censored-box: #2 phar:///usr/local/bin/wp-cli/php/WP_CLI/Runner.php(807): require('phar:///usr/loc...')
==> censored-box: #3 phar:///usr/local/bin/wp-cli/php/WP_CLI/Runner.php(755): WP_CLI\Runner->load_wordpress()
==> censored-box: #4 phar:///usr/local/bin/wp-cli/php/wp-cli.php(21): WP_CLI\Runner->start()
==> censored-box: #5 phar:///usr/local/bin/wp-cli/php/boot-phar.php(5): include('phar:///usr/loc...')
==> censored-box: #6 /usr/local/bin/wp-cli(4): include('phar:///usr/loc...')
==> censored-box: #7 {main}
==> censored-box:   thrown in /data/wordpress/htdocs/wordpress/wp-includes/load.php on line 317
==> censored-box: Remote command execution finished.
    censored-box: Activate git hooks in scripts/hooks? (yes): y
==> censored-box: Executing remote command "wp-activate-git-hooks"...
==> censored-box: Remote command execution finished.
    censored-box: Trust the generated ssl-certificate in OS-X keychain? (yes):
==> censored-box: Executing remote command "wp-use-asset-proxy &> /dev/null"...
==> censored-box: Remote command execution finished.
==> censored-box: Executing remote command "wp-restart-nginx &> /dev/null"...
==> censored-box: Remote command execution finished.

==> trigger: Documentation available at https://docs.wp-palvelu.fi
==> trigger: Visit your site: https://censored.local
________________________________________________________________________________
| ~/Documents/Sites/censored @ Christian-MBP (christian)
| =>
```

The whole vagrant box seems to somehow break when this occurs. Easiest way to fix is just to clone the site again.

**Comment by k1sul1** [comment]
This is _probably_ related to wp-cli being outdated. Trying to run `wp plugin install one-time-login --activate` results in 

```
PHP Fatal error:  Uncaught Error: Call to undefined function apply_filters() in /data/wordpress/htdocs/wordpress/wp-includes/load.php:317
```

Which in turn is caused by WP 4.6. Easy fix is running `sudo wp cli update` on the vagrant machine.

**Comment by anttiviljami** [comment]
Should be fixed by just updating your box.

However it's a good idea to always run wp cli update on provision, just to make sure. I'm not going to close this issue yet.

**Comment by ottok** [comment]
Development boxes should be fairly static and don't change by themselves in general. Otherwise the promise that 'vagrant up' will magically create a identical dev environment for each developer would not hold. For Vagrant the designed way to upgrade, is to run `vagrant box update` so that when developers get an updated server software stack, they all at least get the same new stack.

The originially reported issue is now fixed as WP-CLI is available in the next Vagrant image.
