### ISSUE TITLE
Docker daemon socket permission denied

### ISSUE THREAD

**Issue by JoosuaKoskinen** [Seravo/wp-vagrant#60]
I got the following error running `vagrant ssh`:
```
~ vagrant ssh              
Connecting to development environment... (ssh -- )
Waiting for SSH connection...
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/seravo_wordpress/json: dial unix /var/run/docker.sock: connect: permission denied
Connection to 127.0.0.1 closed.
```

After I while, I got in. But the site doesn't seem to be running at all (`ERR_TIMED_OUT`). I tried running `wp-restart-nginx` but got the same error as with `vagrant up`. The VirtualBox is running fine.

**Env:**
- Ubuntu 20.04 LTS
- Vagrant 2.2.9 + VirtualBox 6.1
- seravo\wordpress-beta v.20200606 box

**Comment by ottok** [comment]
Does vagrant halt + vagrant up make the services restart and work after
that?

**Comment by JoosuaKoskinen** [comment]
It doesn't. The output from `vagrant up` is like this:
```
==> wordpress-box: Starting Seravo WordPress development environment...
==> wordpress-box: 
==> wordpress-box: Starting Seravo WordPress development environment...
==> wordpress-box: Starting Seravo WordPress development environment...
==> wordpress-box: 
==> wordpress-box: Starting Seravo WordPress development environment...
==> wordpress-box: Starting Seravo WordPress development environment...
==> wordpress-box: 
==> wordpress-box: Starting Seravo WordPress development environment...
==> wordpress-box: Starting Seravo WordPress development environment...
==> wordpress-box: Starting Seravo WordPress development environment...
==> wordpress-box: Starting Seravo WordPress development environment...
==> wordpress-box: Starting Seravo WordPress development environment...
==> wordpress-box: Starting Seravo WordPress development environment...
==> wordpress-box: Starting Seravo WordPress development environment...
==> wordpress-box: 
==> wordpress-box: 
==> wordpress-box: 
==> wordpress-box: 
==> wordpress-box: Development environment did not come online in 3 minutes
==> wordpress-box: Skipped running commands (/usr/local/bin/wp-use-asset-proxy)
==> wordpress-box: 
==> wordpress-box: Connecting to development environment... (ssh -- /usr/local/bin/wp-restart-nginx)
==> wordpress-box: 
==> wordpress-box: Waiting for SSH connection...
==> wordpress-box: 
==> wordpress-box: Waiting for SSH connection...
==> wordpress-box: 
==> wordpress-box: Events in past 5 seconds:
==> wordpress-box: Starting Seravo WordPress development environment...
==> wordpress-box: 
==> wordpress-box: Waiting for SSH connection...
==> wordpress-box: 
==> wordpress-box: Waiting for SSH connection...
==> wordpress-box: 
==> wordpress-box: Waiting for SSH connection...
==> wordpress-box: 
==> wordpress-box: Waiting for SSH connection...
==> wordpress-box: 
==> wordpress-box: Waiting for SSH connection...
==> wordpress-box: 
==> wordpress-box: Waiting for SSH connection...

... output like this for very long time ...
```

Does that mean even SSH is not running or what? The VirtualBox has booted fine.

**Comment by JoosuaKoskinen** [comment]
This seems to be because the container is constantly restarting due to `/sbin/swd_init` returning `1`. I found the reason to be https://github.com/Seravo/wp-palvelu-docker/blob/master/bootstrap.d/0000-check-mounts.sh.

`mount` indeed doesn't have a line with `/data`. Output from `df -h /data`:
```
Filesystem      Size  Used Avail Use% Mounted on
overlay         9.7G  2.8G  6.9G  29% /
```

**Comment by JoosuaKoskinen** [comment]
This seems to be happening because the container is constantly restarting due to `swd_init` returning with exit code `1`. That's because of the following error:
```
/usr/share/seravo/bootstrap.d/1330-generate-ssl.sh:
Traceback (most recent call last):
  File "/usr/local/bin/wp-generate-ssl", line 17, in <module>
    sys.exit(main())
  File "/usr/local/bin/wp-generate-ssl", line 13, in main
    return wp_generate_ssl()
  File "ssl_util.py", line 117, in wp_generate_ssl
  File "config.py", line 54, in __init__
seravo.config.ConfigError: Configuration must be a dictionary.
run-parts: /usr/share/seravo/bootstrap.d/1330-generate-ssl.sh exited with return code 1
```

**Comment by JoosuaKoskinen** [comment]
I checked the `config.yml` in the Vagrant box and it has just `1` in it. I use https://github.com/Seravo/wordpress and the default configs that come with it. I don't know why the config.yml in the box has just `1` in it.

**Comment by ottok** [comment]
If you don't have any config.yml, then a default one will be written by the Ruby code in Vagrantfile.

Please delete the bogus config.yml and see if next invocation of `vagrant up` re-creates it?

**Comment by JoosuaKoskinen** [comment]
I destroyed and cleaned up everything and it's still the case.

Everything is as supposed to be in the beginning:
```
~ stat config.yml      
stat: cannot stat 'config.yml': No such file or directory

~ cat config-sample.yml
###
# Configuration for development environment (Vagrant and Docker)
###
name: wordpress
#production:
  # This is used to automatically fetch data from a staging/production environment
  #domain: example.seravo.com
  #ssh_port: 12345
  #url: https://example.seravo.com
development:
  # Domains are automatically mapped to Vagrant with /etc/hosts modifications or Avahi
  domains:
    - wordpress.local
  # Allow Vagrant to expose .local domains on the local network (outside of laptop)
  #avahi: true
  # If you want to automatically pull stuff from production use 'always' or set
  # to 'never' to just silence the 'yes/no' question during 'vagrant up'.
  #pull_production_db: always
  #pull_production_plugins: always
  #pull_production_themes: always
```

But in Vagrant box the config file has changed:
```
~ vagrant up
.....

~ vagrant ssh
vagrant@seravo-wordpress:~$ cat /data/wordpress/config.yml 
1
```

**Comment by ottok** [comment]
This should be fixed or at least mitigated in the latest seravo/wordpress-beta box version 20200610.0.0. Please test again.

**Comment by JoosuaKoskinen** [comment]
> This should be fixed or at least mitigated in the latest seravo/wordpress-beta box version 20200610.0.0. Please test again.

Seems to be fixed in the latest seravo/wordpress-beta box :+1:
